=== corentinleroux/M1_FRAMEWORK_JMS/jms-04/jms04-models/bin/src/main/xsd/models.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation xml:lang="eb">
			Generated Models
		</xsd:documentation>
	</xsd:annotation>


	<xsd:element name="diplomaInfo" type="DiplomaInfo"></xsd:element>


	<xsd:complexType name="DiplomaInfo">
		<xsd:sequence>
			<xsd:element name="id" type="xsd:int"></xsd:element>
			<xsd:element name="student" type="Student"></xsd:element>
			<xsd:element name="grade" type="xsd:double"></xsd:element>
			<xsd:element name="major" type="xsd:string"></xsd:element>
		</xsd:sequence>

	</xsd:complexType>

	<xsd:complexType name="Student">
		<xsd:sequence>
			<xsd:element name="id" type="xsd:int"></xsd:element>
			<xsd:element name="firstName" type="xsd:string"></xsd:element>
			<xsd:element name="lastName" type="xsd:string"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>



</xsd:schema>

=== corentinleroux/M1_FRAMEWORK_JMS/jms-04/jms04-models/bin/src/test/xml/student.xml
<?xml version="1.0" encoding="UTF-8"?><diplomaInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../main/xsd/models.xsd">  <id>1</id>  <student>    <id>2606</id>    <firstName>Nicolas</firstName>    <lastName>Herbaut</lastName>  </student>  <grade>10.0</grade>  <major>CS</major></diplomaInfo>
